'use client';
import { useEffect, useMemo, useState } from 'react';
import { Plus, Save, Trash2, RotateCcw } from 'lucide-react';
import { seedTools, type Tool } from '@/lib/tools';
const KEY='atlas-tools-preview-v1';
export default function Admin(){
 const [tools,setTools]=useState<Tool[]>(seedTools); const [selected,setSelected]=useState<string>(seedTools[0].id); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setTools(JSON.parse(raw))}catch{}},[]);
 const current=useMemo(()=>tools.find(t=>t.id===selected)||tools[0],[tools,selected]);
 const update=(patch:Partial<Tool>)=>setTools(xs=>xs.map(t=>t.id===selected?{...t,...patch}:t));
 const save=()=>{localStorage.setItem(KEY,JSON.stringify(tools));setSaved(true);setTimeout(()=>setSaved(false),1400)};
 const add=()=>{const id=`custom-${Date.now()}`;const t:Tool={id,name:'أداة جديدة',vendor:'شركة جديدة',category:'chat',logo:'AI',hook:'وصف قصير يجذب المستخدم',description:'وصف الأداة وتفاصيل استخدامها.',website:'https://example.com',featured:false,plans:[]};setTools(xs=>[t,...xs]);setSelected(id)};
 const remove=()=>{if(tools.length<=1)return;const next=tools.filter(t=>t.id!==selected);setTools(next);setSelected(next[0].id)};
 const reset=()=>{localStorage.removeItem(KEY);setTools(seedTools);setSelected(seedTools[0].id)};
 if(!current) return null;
 return <div className="mx-auto max-w-7xl px-5 md:px-8 pt-32 pb-24"><div className="flex flex-col md:flex-row md:items-end justify-between gap-5 mb-7"><div><div className="text-xs tracking-[.18em] text-gold">ADMIN / PREVIEW MODE</div><h1 className="mt-2 text-4xl font-extrabold">إدارة أطلس</h1><p className="mt-2 text-sm text-muted">هذه النسخة تعمل محليًا للمعاينة. ربط Supabase مرفق ضمن المشروع للإنتاج.</p></div><div className="flex gap-2"><button onClick={add} className="px-4 py-3 rounded-2xl bg-white/5 hover:bg-white/10"><Plus size={17}/></button><button onClick={reset} className="px-4 py-3 rounded-2xl bg-white/5 hover:bg-white/10"><RotateCcw size={17}/></button><button onClick={save} className="px-5 py-3 rounded-2xl bg-gold text-[#090A0F] font-bold"><Save size={17} className="inline ml-1"/> {saved?'تم الحفظ':'حفظ محلي'}</button></div></div><div className="grid lg:grid-cols-[300px_1fr] gap-5"><aside className="glass rounded-3xl p-3 h-fit">{tools.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} className={`w-full text-right rounded-2xl px-4 py-3 mb-1 ${t.id===selected?'bg-gold text-[#090A0F] font-bold':'hover:bg-white/5 text-muted'}`}>{t.name}</button>)}</aside><section className="glass rounded-3xl p-6"><div className="grid md:grid-cols-2 gap-5">{[['name','اسم الأداة'],['vendor','الشركة'],['logo','الاختصار'],['website','الرابط الرسمي'],['hook','الجملة القصيرة'],['description','الوصف']].map(([key,label])=><label key={key} className="block"><span className="text-xs text-muted">{label}</span>{key==='description'?<textarea value={String(current[key as keyof Tool])} onChange={e=>update({[key]:e.target.value} as Partial<Tool>)} className="mt-2 min-h-28 w-full rounded-2xl border border-white/8 bg-black/20 p-3 outline-none focus:border-gold/30"/>:<input value={String(current[key as keyof Tool])} onChange={e=>update({[key]:e.target.value} as Partial<Tool>)} className="mt-2 w-full rounded-2xl border border-white/8 bg-black/20 p-3 outline-none focus:border-gold/30"/>}</label>)}<label className="flex items-center gap-3 rounded-2xl bg-white/5 p-4"><input type="checkbox" checked={current.featured} onChange={e=>update({featured:e.target.checked})}/><span>عرض الأداة ضمن الأدوات المميزة</span></label><div className="flex justify-end"><button onClick={remove} className="px-4 py-3 rounded-2xl text-red-300 bg-red-400/5 hover:bg-red-400/10"><Trash2 size={16} className="inline ml-1"/> حذف الأداة</button></div></div></section></div></div>
}
