import { $ } from './lib/dom.js';
import { initTheme } from './modules/theme.js';
import { initReveal } from './modules/reveal.js';
import { initSpotlight } from './modules/spotlight.js';
import { initScrollProgress, initToTop } from './modules/scroll-progress.js';
import { initScrollSpy } from './modules/scrollspy.js';
import { initPricing } from './modules/pricing.js';
import { initLightbox } from './modules/lightbox.js';
import { initBars } from './modules/bars.js';
import { initFab } from './modules/fab.js';
import { initFit } from './modules/fit.js';
import { initHud } from './modules/hud.js';
import { initLangSwitch } from './modules/lang-switch.js';

initTheme($('[data-theme-toggle]'));
initLangSwitch();
initReveal();
initSpotlight();
initScrollProgress($('.read-progress'));
initToTop($('.to-top'));
initScrollSpy($('.subnav'));
initPricing();
initLightbox();
initBars();
initFab();
initFit();
initHud();
