import Link from 'next/link';
import { ArrowLeft, BadgeCheck, Layers3, MessageCircle, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import SectionHeading from '@/components/SectionHeading';
import ToolsExplorer from '@/components/ToolsExplorer';

export default function Home(){
 return <div className="atlas-shell"><div className="absolute inset-x-0 top-0 h-[900px] atlas-grid pointer-events-none"/>
  <section className="relative pt-36 pb-24 md:pt-48 md:pb-32"><div className="mx-auto max-w-7xl px-5 md:px-8 grid lg:grid-cols-[1.05fr_.95fr] gap-14 items-center">
    <div><div className="inline-flex items-center gap-2 rounded-full border border-gold/20 bg-gold/5 px-4 py-2 text-xs text-gold"><Sparkles size={14}/> الدليل العربي المرجعي لأدوات الذكاء الاصطناعي</div>
      <h1 className="mt-7 text-5xl md:text-7xl font-extrabold leading-[1.05] tracking-tight text-glow">كل أدوات الذكاء الاصطناعي.<br/><span className="text-gold">مرتبة. واضحة. بالعربي.</span></h1>
      <p className="mt-7 max-w-2xl text-lg leading-9 text-muted">اكتشف الأداة المناسبة لشغلك، افهم الفرق بين الخطط، وشوف آخر المعلومات قبل ما تدفع. بدون ضياع بين عشرات المواقع والصفحات الإنجليزية.</p>
      <div className="mt-9 flex flex-col sm:flex-row gap-3"><Link href="/tools" className="rounded-2xl bg-gold text-[#090A0F] px-6 py-4 font-extrabold text-center hover:brightness-110 transition">استكشف الأدوات <ArrowLeft className="inline mr-2" size={18}/></Link><Link href="/contact" className="rounded-2xl border border-white/10 px-6 py-4 font-bold text-center hover:bg-white/5 transition">أريد المساعدة بالاختيار</Link></div>
      <div className="mt-10 grid grid-cols-3 gap-3 max-w-xl">{[['15+','أداة مختارة'],['6','فئات رئيسية'],['24/7','وصول مباشر']].map(([a,b])=><div key={a} className="glass rounded-2xl p-4"><div className="font-mono text-xl text-gold">{a}</div><div className="text-xs text-muted mt-1">{b}</div></div>)}</div>
    </div>
    <div className="relative"><div className="absolute -inset-12 bg-purple/10 blur-3xl rounded-full"/><div className="relative glass rounded-[36px] p-5 md:p-7 shadow-purple-glow"><div className="rounded-[28px] border border-white/7 bg-black/20 p-5"><div className="flex items-center justify-between"><div><div className="text-xs text-muted">ATLAS INTELLIGENCE INDEX</div><div className="mt-1 text-2xl font-extrabold">اختيارك يبدأ من هنا</div></div><div className="h-11 w-11 rounded-full bg-gold/10 border border-gold/25 grid place-items-center text-gold"><Zap size={19}/></div></div><div className="mt-6 space-y-3">{[['بحث وموثوقية','Perplexity','92%'],['محتوى وكتابة','Claude','96%'],['تصميم بصري','Midjourney','94%'],['تطوير وبرمجة','Copilot','95%']].map(([a,b,c])=><div key={b} className="rounded-2xl border border-white/7 bg-white/[.025] p-4"><div className="flex justify-between text-sm"><span>{a}</span><span className="text-gold">{b}</span></div><div className="mt-3 h-1.5 rounded-full bg-white/5 overflow-hidden"><div className="h-full rounded-full bg-gradient-to-r from-purple to-gold" style={{width:c}}/></div><div className="mt-2 text-[11px] text-muted">ملاءمة تجريبية للعرض — ليست توصية مطلقة</div></div>)}</div></div></div></div>
  </div></section>
  <section className="pb-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionHeading eyebrow="المميز الآن" title="أدوات تستحق تكون عندك" desc="عرض سريع لأهم الأدوات. اضغط على أي بطاقة لتشوف شرحها، خططها، ورابطها الرسمي."/><ToolsExplorer compact/><div className="mt-7 text-center"><Link href="/tools" className="text-gold text-sm hover:underline">عرض كل الأدوات ←</Link></div></div></section>
  <section className="py-24 border-y border-white/5"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionHeading eyebrow="لماذا أطلس؟" title="مو مجرد دليل أدوات جميل" desc="الفكرة الأساسية هي جعل اكتشاف الأداة خطوة مفيدة تقودك للقرار، مو مجرد تصفح لا ينتهي."/><div className="grid md:grid-cols-3 gap-5">{[[ShieldCheck,'معلومات أوضح','عرض عربي مختصر يشرح متى تستخدم الأداة ولمن تناسب.'],[BadgeCheck,'ثقة أعلى','إظهار تاريخ التحقق ومصدر السعر بدل تقديم رقم قديم وكأنه حقيقة ثابتة.'],[MessageCircle,'طريق مباشر','لما تحتاج مساعدة فعلية، تنتقل من المعلومة إلى التواصل مباشرة.']].map(([I,t,d])=>{const Icon=I as any;return <div key={t as string} className="glass rounded-3xl p-6"><div className="h-12 w-12 rounded-2xl bg-gold/10 border border-gold/20 grid place-items-center text-gold"><Icon size={22}/></div><h3 className="mt-5 text-xl font-bold">{t as string}</h3><p className="mt-3 text-sm text-muted leading-7">{d as string}</p></div>})}</div></div></section>
  <section className="py-24"><div className="mx-auto max-w-5xl px-5 md:px-8"><div className="relative overflow-hidden glass rounded-[36px] p-8 md:p-12 text-center"><div className="absolute -top-24 left-1/2 -translate-x-1/2 h-64 w-64 bg-gold/10 blur-3xl rounded-full"/><div className="relative"><Layers3 className="mx-auto text-gold" size={34}/><h2 className="mt-5 text-3xl md:text-5xl font-extrabold">جاهز تبدأ؟</h2><p className="mt-4 text-muted leading-8 max-w-2xl mx-auto">تواصل معنا مباشرة ونساعدك تختار وتفعّل الأداة الأنسب لك، بأفضل شكل وبخطوات واضحة.</p><div className="mt-8 flex flex-col sm:flex-row justify-center gap-3"><Link href="/contact" className="rounded-2xl bg-gold text-[#090A0F] px-6 py-4 font-extrabold">تواصل عبر واتساب</Link><Link href="/pricing" className="rounded-2xl border border-white/10 px-6 py-4 font-bold">قارن الأسعار</Link></div></div></div></div></section>
  <footer className="border-t border-white/5 py-8 text-center text-xs text-muted">أطلس © 2026 — دليل عربي لأدوات الذكاء الاصطناعي</footer>
 </div>
}
