'use client';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,BarChart3,Bitcoin,CheckCircle2,CircleSlash2,Clock3,ShieldAlert,ShieldCheck,Target,TrendingDown,TrendingUp} from 'lucide-react';
import {analyze,DEFAULT_CONFIG,generateDemoCandles,positionSize,RULEBOOK,Analysis,Candle} from '@/lib/talaria-engine';
import {fetchOkxCandles,OKX_SYMBOLS,subscribeOkxCandles} from '@/lib/okx-market';

const fmt=(n:number,d=2)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n);
const statusLabel=(s:string)=>s.replaceAll('_',' ');
function useOkxMarket(instId:string,timeframe='5m'){
 const [candles,setCandles]=useState<Candle[]>([]);const [status,setStatus]=useState<'loading'|'rest'|'live'|'error'>('loading');
 useEffect(()=>{let alive=true;let stop:undefined|(()=>void);fetchOkxCandles(instId,timeframe,300).then(xs=>{if(!alive)return;setCandles(xs);setStatus('rest');}).catch(()=>alive&&setStatus('error'));stop=subscribeOkxCandles(instId,timeframe,c=>{if(!alive)return;setCandles(prev=>{const next=prev.slice();const i=next.findIndex(x=>x.time===c.time);if(i>=0)next[i]=c;else next.push(c);return next.slice(-600);});setStatus('live');});return()=>{alive=false;stop?.();};},[instId,timeframe]);return {candles,status};
}
function MiniChart({candles}:{candles:Candle[]}){const c=candles.slice(-80);if(!c.length)return <div className="chart-empty">No market bars</div>;const min=Math.min(...c.map(x=>x.low)),max=Math.max(...c.map(x=>x.high));const points=c.map((x,i)=>`${(i/Math.max(c.length-1,1))*100},${96-((x.close-min)/(max-min||1))*88}`).join(' ');return <svg viewBox="0 0 100 100" className="chart"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/></svg>}
function MarketCard({a,candles,status,name,icon}:{a:Analysis;candles:Candle[];status:string;name:string;icon:React.ReactNode}){return <div className="panel market-card"><div className="market-title"><div className="market-symbol">{icon}<div><b>{name}</b><small>OKX · 5m · closed bars</small></div></div><span className="live-label">{status.toUpperCase()}</span></div><MiniChart candles={candles}/><div className="market-foot"><strong>{fmt(a.entry,a.symbol==='XAUUSD'?2:0)}</strong><span className={a.bias==='BULLISH'?'bull':a.bias==='BEARISH'?'bear':'muted'}>{a.bias==='BULLISH'?<TrendingUp size={15}/>:a.bias==='BEARISH'?<TrendingDown size={15}/>:<Clock3 size={15}/>} {a.bias}</span></div><div className="metric-strip"><span>Structure <b>{a.structure.bos?'BOS':'—'}</b></span><span>Sweep <b>{a.sweep?'YES':'NO'}</b></span><span>FVG <b>{a.fvg?'YES':'NO'}</b></span><span>OTE <b>{a.ote?'YES':'NO'}</b></span></div></div>}
function SignalCard({a}:{a:Analysis}){return <div className="panel signal-card"><div className="signal-head"><div><span className={a.side==='LONG'?'pill green':a.side==='SHORT'?'pill red':'pill'}>{a.side||'WAIT'}</span><b>{a.symbol}</b><small>{a.timeframe}</small></div><div className="grade">{a.grade||'NO-TRADE'}</div></div><div className="price-grid"><div><small>Entry</small><strong>{fmt(a.entry,a.symbol==='XAUUSD'?2:0)}</strong></div><div><small>SL</small><strong>{fmt(a.sl,a.symbol==='XAUUSD'?2:0)}</strong></div><div><small>TP</small><strong>{fmt(a.tp,a.symbol==='XAUUSD'?2:0)}</strong></div><div><small>RRR</small><strong>{a.rrr.toFixed(2)}R</strong></div></div><div className="chips">{a.components.map(x=><span key={x}>{x}</span>)}</div><div className={a.status==='SIGNAL'?'decision ready':'decision'}>{a.status==='SIGNAL'?<><ShieldCheck size={17}/> {a.strategy} · {a.score}/100 · {statusLabel(a.reason)}</>:<><AlertTriangle size={17}/> NO TRADE · {statusLabel(a.reason)}</>}</div>{a.noTradeReasons.length>0&&<div className="reason-list">{a.noTradeReasons.slice(0,8).map(x=><span key={x}>{statusLabel(x)}</span>)}</div>}</div>}
function StrategyMatrix({a}:{a:Analysis}){return <div className="strategy-table">{a.strategyEvaluations.map(e=><div className="strategy-row" key={e.strategy}><div><b>{e.strategy}</b><small>{e.family}</small></div><span className={e.status==='SIGNAL'?'state ok':e.status==='NO_TRADE'?'state wait':'state bad'}>{statusLabel(e.status)}</span><strong>{e.grade||'—'}</strong><span>{e.side||'—'}</span><span>{e.rrr?`${e.rrr.toFixed(2)}R`:'—'}</span><small>{statusLabel(e.reason)}</small></div>)}</div>}
function Audit({a}:{a:Analysis}){const grouped=['L1-3','L4-6','L7-9','HERMES'] as const;return <div className="audit-grid">{grouped.map(scope=>{const rows=a.ruleTrace.filter(x=>x.scope===scope);const passed=rows.filter(x=>x.passed).length;return <div className="panel audit-panel" key={scope}><div className="section-head"><div><span className="eyebrow">RULE TRACE</span><h3>{scope}</h3></div><span>{passed}/{rows.length}</span></div>{rows.map(r=><div className="audit-row" key={`${scope}-${r.id}`}><span className={r.passed?'audit-dot pass':'audit-dot'}>{r.passed?'✓':'·'}</span><b>{r.id}</b><span>{r.status}</span><small>{r.reason}</small></div>)}</div>})}</div>}
export default function TalariaDashboard(){
 const [tab,setTab]=useState<'dashboard'|'strategies'|'audit'|'risk'>('dashboard');const [balance,setBalance]=useState(10000);const [risk,setRisk]=useState(.5);
 const btcM=useOkxMarket(OKX_SYMBOLS.BTCUSD.instId,'5m');const xauM=useOkxMarket(OKX_SYMBOLS.XAUUSD.instId,'5m');
 const btcCandles=btcM.candles.length?btcM.candles:generateDemoCandles(41,180,65000);const xauCandles=xauM.candles.length?xauM.candles:generateDemoCandles(83,180,2350);
 const baseCfg={...DEFAULT_CONFIG,riskPct:risk};const btc=useMemo(()=>analyze('BTCUSD',btcCandles,'5m',baseCfg,{risk:{accountBalance:balance,currentRiskPct:risk}}),[btcCandles,balance,risk]);const xau=useMemo(()=>analyze('XAUUSD',xauCandles,'5m',baseCfg,{risk:{accountBalance:balance,currentRiskPct:risk}}),[xauCandles,balance,risk]);
 const btcSize=positionSize(balance,risk,btc.entry||65000,btc.sl||64000,.001);const xauSize=positionSize(balance,risk,xau.entry||2350,xau.sl||2320,1);
 const selected=btc.strategy?btc:xau.strategy?xau:btc;const sourceCounts=useMemo(()=>RULEBOOK.reduce((m,r)=>{m[r.status]=(m[r.status]??0)+1;return m},{} as Record<string,number>),[]);
 return <main className="talaria-shell"><header className="topbar"><div className="brand"><div className="brand-mark">T</div><div><strong>TALARIA</strong><small>Source-faithful institutional engine</small></div></div><div className="live"><span className="dot"/> OKX {btcM.status==='live'&&xauM.status==='live'?'LIVE':'MARKET DATA'} <span>UTC</span></div></header>
 <section className="hero"><div><div className="eyebrow">OKX · LEVELS 1–9 · HERMES · MTF · LIQUIDITY · RISK GOVERNANCE</div><h1>BTC & GOLD <em>decision engine.</em></h1><p>Closed OKX candles feed the source-derived structure, liquidity, strategy dispatcher, NO-TRADE gates and auditable signal object.</p></div><div className="hero-stat"><span>ACCOUNT</span><b>${fmt(balance)}</b><small>Current risk {risk.toFixed(2)}%</small></div></section>
 <nav className="tabs">{(['dashboard','strategies','audit','risk'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='dashboard'&&<><section className="market-grid"><MarketCard a={btc} candles={btcCandles} status={btcM.status} name="BTC-USDT" icon={<Bitcoin size={19}/>}/><MarketCard a={xau} candles={xauCandles} status={xauM.status} name="XAU-USDT-SWAP · Gold" icon={<BarChart3 size={19}/>}/></section><section className="section-head"><div><span className="eyebrow">SIGNAL BOARD</span><h2>Qualified setups</h2></div><span className="gate"><ShieldCheck size={16}/> {selected.status==='SIGNAL'?'SIGNAL READY':'NO-TRADE GATE ACTIVE'}</span></section><div className="signals"><SignalCard a={btc}/><SignalCard a={xau}/></div></>}
 {tab==='strategies'&&<section className="panel strategy-panel"><div className="section-head"><div><span className="eyebrow">STRATEGY DISPATCHER</span><h2>All source-defined modules</h2></div><span>{btc.strategyEvaluations.length} modules</span></div><StrategyMatrix a={selected}/><div className="source-status"><div><CheckCircle2 size={16}/><b>SOURCE RULE</b><span>{sourceCounts.SOURCE_RULE||0}</span></div><div><ShieldAlert size={16}/><b>REQUIRES BACKTEST</b><span>{sourceCounts.REQUIRES_BACKTEST||0}</span></div><div><CircleSlash2 size={16}/><b>REJECTED</b><span>{sourceCounts.REJECTED||0}</span></div><div><Target size={16}/><b>DATA DEPENDENT</b><span>{sourceCounts.DATA_DEPENDENT||0}</span></div></div></section>}
 {tab==='audit'&&<><section className="section-head"><div><span className="eyebrow">AUDITABILITY</span><h2>Rule-by-rule trace</h2></div><span>Selected: {selected.symbol}</span></section><Audit a={selected}/></>}
 {tab==='risk'&&<section className="risk-layout"><div className="panel risk-panel"><span className="eyebrow">RISK ENGINE</span><h2>Source risk policy</h2><label>Account balance<input type="number" value={balance} onChange={e=>setBalance(Number(e.target.value)||0)}/></label><label>Risk / trade <b>{risk.toFixed(2)}%</b><input type="range" min="0.1" max="2" step="0.1" value={risk} onChange={e=>setRisk(Number(e.target.value))}/></label><div className="guard-grid"><div><small>Base risk</small><b>0.5%</b></div><div><small>Max risk</small><b>2.0%</b></div><div><small>Daily core cap</small><b>2</b></div><div><small>Absolute cap</small><b>3</b></div><div><small>Loss breaker</small><b>3</b></div><div><small>Demon lock</small><b>10</b></div></div><div className="risk-notice"><AlertTriangle size={17}/><span>The supplied corpus contains module-specific conflicts (2 vs 3 daily trades, 1% vs dynamic 0.5–2% risk, and different RRR thresholds). The engine keeps policy at module level rather than silently merging them.</span></div></div><div className="panel sizing"><span className="eyebrow">POSITION SIZING</span><h2>Calculated risk exposure</h2><div className="size-row"><span>BTC-USDT</span><b>{btcSize.toFixed(4)} units</b></div><div className="size-row"><span>XAU-USDT-SWAP</span><b>{xauSize.toFixed(4)} contracts</b></div><p>Broker contract size, point value, tick value and currency conversion must be supplied before any live execution layer can trust the computed size.</p></div></section>}
 <footer><span>TALARIA · rulebook-driven · closed-bar only</span><span>Missing macro/COT/news data is never invented · AI is advisory/audit only</span></footer></main>
}
