export type Side = 'LONG' | 'SHORT';
export type Strategy = 'PCR' | 'SIREN' | 'SNAKE' | 'SAC' | 'WICK' | 'MDS' | 'OSOK' | 'OFFSET_IFVG' | 'ASIAN_SCALP' | 'NY_SCALP';
export type Grade = 'A+' | 'A' | 'B' | null;
export type ValidationStatus = 'SIGNAL' | 'NO_TRADE' | 'INVALIDATED' | 'CANCELLED';
export type RuleStatus = 'SOURCE_RULE' | 'ENGINEERING_ADDITION' | 'REQUIRES_BACKTEST' | 'UNVERIFIED' | 'REJECTED' | 'DATA_DEPENDENT';
export type Scope = 'L1-3' | 'L4-6' | 'L7-9' | 'HERMES';

export interface Candle { time: number; open: number; high: number; low: number; close: number; volume: number }
export interface Zone { type: string; top: number; bottom: number; mt: number; timeframe: string; valid: boolean }
export interface LiquidityPool { type: 'BSL'|'SSL'|'EQH'|'EQL'|'PDH'|'PDL'|'PWH'|'PWL'|'ASIAN_HIGH'|'ASIAN_LOW'; price: number; time: number; strength: 'STRONG'|'WEAK' }
export interface StructureSnapshot {
  bias: 'BULLISH'|'BEARISH'|'NEUTRAL';
  bullishFourPoint: boolean; bearishFourPoint: boolean;
  strongHigh: number|null; strongLow: number|null; weakHigh: number|null; weakLow: number|null;
  bos: boolean; mss: boolean; choch: boolean; insideBarsNeutralized: number;
  protectedIth: number|null; protectedItl: number|null;
}
export interface MacroContext {
  us10yTrend?: 'RISING'|'FALLING'|'FLAT'; znTrend?: 'RISING'|'FALLING'|'FLAT'; dxyTrend?: 'BULLISH'|'BEARISH'|'FLAT';
  znDxySyncDays?: number; dxySmt?: boolean; newsLock?: boolean;
  cot52WeekCommercialPercentile?: number; cotAligned?: boolean; cotBiasLockSide?: Side; cotLockDaysRemaining?: number;
  openInterestDrainPct?: number; commoditiesBias?: 'BULLISH'|'BEARISH'|'NEUTRAL'; auctionTailWide?: boolean;
  seasonality20Y?: number[]; seasonality10Y?: number[]; seasonalityConsensusDays?: number; seasonalitySafetyDays?: number;
  eurGbpBias?: 'EUR_STRONGER'|'EUR_WEAKER'|'NEUTRAL';
}
export interface WeeklyContext { template?: 'CLASSIC_TUESDAY_LOW'|'WEDNESDAY_LOW'|'THURSDAY_REVERSAL_CONSOLIDATION'|'MIDWEEK_RALLY'|'SEEK_AND_DESTROY'|'WEDNESDAY_FALSE_SHIFT'|'UNKNOWN'; osokTradesTakenThisWeek?: number }
export interface VolatilityContext { cbdrRangePips?: number; adr5Pips?: number; londonConsumedPips?: number; spread?: number; averageSpread?: number; slippage?: number; averageSlippage?: number }
export interface RiskState { accountBalance:number; currentRiskPct:number; dailyLossPct:number; dailyTrades:number; maxDailyTrades:number; consecutiveLosses:number; maxConsecutiveLosses:number; consecutiveWins:number; demonStrikes:number; maxDemonStrikes:number; weeklyOsokTrades:number; maxWeeklyOsokTrades:number; tradingEnabled:boolean }
export interface EngineContext { now?:number; elapsedFraction?:number; macro?:MacroContext; weekly?:WeeklyContext; volatility?:VolatilityContext; risk?:Partial<RiskState>; asiaHigh?:number; asiaLow?:number }
export interface EngineConfig {
  riskPct:number; dailyLossLimitPct:number; maxDailyTrades:number; maxConsecutiveLosses:number; minRRR:number; preferredRRR:number;
  dailyCoreTradeCap:number; scalpMinRRR:number; mdsOsokMinRRR:number; baseRiskPct:number; maxRiskPct:number; halfToleranceRiskPct:number;
}
export interface RuleEntry { scope:Scope; id:string; status:RuleStatus; title:string }
export interface RuleTrace { scope:Scope; id:string; status:RuleStatus; passed:boolean; reason:string }
export interface StrategyEvaluation {
  strategy:Strategy; family:string; applicable:boolean; status:ValidationStatus; side:Side|null; entry:number; sl:number; tp:number;
  rrr:number; score:number; grade:Grade; reason:string; ruleIds:string[]; ruleStatuses:RuleStatus[]; components:string[]; warnings:string[];
}
export interface Analysis {
  symbol:string; timeframe:string; side:Side|null; bias:'BULLISH'|'BEARISH'|'NEUTRAL';
  bos:boolean; mss:boolean; sweep:boolean; fvg:boolean; orderBlock:boolean; breaker:boolean; ote:boolean;
  liquidity:string; dol:string; grade:Grade; rrr:number; entry:number; sl:number; tp:number; strategy:Strategy|null;
  status:ValidationStatus; reason:string; score:number; components:string[]; structure:StructureSnapshot; zones:Zone[]; liquidityPools:LiquidityPool[];
  dolTarget:number|null; rrrPolicy:string; strategyEvaluations:StrategyEvaluation[]; ruleTrace:RuleTrace[]; noTradeReasons:string[];
  state:string; risk:RiskState; sourceWarnings:string[];
}

export const DEFAULT_CONFIG:EngineConfig = {
  riskPct:0.5, dailyLossLimitPct:2, maxDailyTrades:3, maxConsecutiveLosses:3, minRRR:2.5, preferredRRR:3,
  dailyCoreTradeCap:2, scalpMinRRR:1.5, mdsOsokMinRRR:3, baseRiskPct:0.5, maxRiskPct:2, halfToleranceRiskPct:0.5,
};

export const RULEBOOK: readonly RuleEntry[] = [
  // L1-3
  ['L1-3','RULE-A01','SOURCE_RULE','Bullish four-point structure'],['L1-3','RULE-A02','SOURCE_RULE','Bearish four-point structure'],['L1-3','RULE-A03','SOURCE_RULE','Candle-by-candle fractal'],['L1-3','RULE-A04','SOURCE_RULE','Strong vs weak extremes'],['L1-3','RULE-A05','SOURCE_RULE','Three-layer hierarchy'],['L1-3','RULE-A06','SOURCE_RULE','Engulfing resolution'],
  ['L1-3','RULE-B01','SOURCE_RULE','Daily directional bias'],['L1-3','RULE-B02','SOURCE_RULE','Macro sweep reversal'],['L1-3','RULE-B03','SOURCE_RULE','Neutral/consolidation'],['L1-3','RULE-B04','SOURCE_RULE','COT directional alignment'],
  ['L1-3','RULE-C01','SOURCE_RULE','Three-candle swing fractal'],['L1-3','RULE-C02','SOURCE_RULE','ITH/ITL'],['L1-3','RULE-C03','SOURCE_RULE','LTH/LTL'],['L1-3','RULE-C04','ENGINEERING_ADDITION','ATR noise filter'],
  ['L1-3','RULE-D01','SOURCE_RULE','BSL'],['L1-3','RULE-D02','SOURCE_RULE','SSL'],['L1-3','RULE-D03','SOURCE_RULE','PDH/PDL/PWH/PWL/Asian levels'],['L1-3','RULE-D04','SOURCE_RULE','LRLR route'],
  ['L1-3','RULE-E01','SOURCE_RULE','Wick sweep'],['L1-3','RULE-E02','SOURCE_RULE','Sweep anchor'],['L1-3','RULE-E03','SOURCE_RULE','Sweep invalidation'],
  ['L1-3','RULE-F01','SOURCE_RULE','Trendline inducement'],['L1-3','RULE-F02','SOURCE_RULE','Pre-POI inducement'],['L1-3','RULE-F03','SOURCE_RULE','Early-entry suppression'],
  ['L1-3','RULE-G01','SOURCE_RULE','BOS'],['L1-3','RULE-G02','SOURCE_RULE','CHoCH/MSS'],['L1-3','RULE-G03','SOURCE_RULE','Double confirmation'],
  ['L1-3','RULE-H01','SOURCE_RULE','High-probability OB'],['L1-3','RULE-H02','SOURCE_RULE','OB 50% MT safety'],['L1-3','RULE-H03','SOURCE_RULE','Breaker'],['L1-3','RULE-H04','SOURCE_RULE','Mitigation'],['L1-3','RULE-H05','SOURCE_RULE','3-candle FVG'],
  ['L1-3','RULE-I01','SOURCE_RULE','OTE 62/70.5/79'],['L1-3','RULE-I02','SOURCE_RULE','OTE construction'],['L1-3','RULE-I03','SOURCE_RULE','OTE invalidation'],
  ['L1-3','RULE-J01','SOURCE_RULE','Limit order entry'],['L1-3','RULE-J02','SOURCE_RULE','Structural SL'],['L1-3','RULE-J03','SOURCE_RULE','Opposite LRLR TP / RRR'],
  ['L1-3','RULE-K01','SOURCE_RULE','Position sizing'],['L1-3','RULE-K02','SOURCE_RULE','Trader-F dynamic risk'],['L1-3','RULE-K03','SOURCE_RULE','Daily trade/loss cap'],['L1-3','RULE-K04','SOURCE_RULE','Anti-Martingale'],['L1-3','RULE-K05','SOURCE_RULE','BE + partial close'],
  ['L1-3','RULE-L01','SOURCE_RULE','New York time normalization'],['L1-3','RULE-L02','SOURCE_RULE','London/NY killzones'],['L1-3','RULE-L03','SOURCE_RULE','Out-of-session lock'],
  ['L1-3','RULE-M01','SOURCE_RULE','SMT divergence'],['L1-3','RULE-M02','SOURCE_RULE','Red-folder news lock'],
  // L4-6
  ['L4-6','RULE-A01','SOURCE_RULE','Bullish order-flow continuation'],['L4-6','RULE-A02','SOURCE_RULE','Order-flow reversal'],['L4-6','RULE-A03','SOURCE_RULE','Unmitigated range'],['L4-6','RULE-B01','SOURCE_RULE','IPDA cycle'],['L4-6','RULE-B02','SOURCE_RULE','20/40/60 lookbacks'],['L4-6','RULE-B03','SOURCE_RULE','DOL'],['L4-6','RULE-C01','SOURCE_RULE','MMXM'],['L4-6','RULE-C02','SOURCE_RULE','Two-timeframe step-up'],['L4-6','RULE-D01','SOURCE_RULE','Premium PD Arrays'],['L4-6','RULE-D02','SOURCE_RULE','Discount PD Arrays'],['L4-6','RULE-D03','SOURCE_RULE','First Line of Defense'],['L4-6','RULE-D04','SOURCE_RULE','Propulsion block'],['L4-6','RULE-D05','SOURCE_RULE','Breakaway vacuum gap'],['L4-6','RULE-E01','SOURCE_RULE','ERL to IRL'],['L4-6','RULE-E02','SOURCE_RULE','IRL to ERL'],['L4-6','RULE-E03','SOURCE_RULE','Mid-range lockout'],['L4-6','RULE-F01','SOURCE_RULE','ZN/US10Y/DXY'],['L4-6','RULE-F02','SOURCE_RULE','High-velocity trend'],['L4-6','RULE-F03','SOURCE_RULE','5-day consolidation predictor'],['L4-6','RULE-F04','SOURCE_RULE','Bond/DXY SMT'],['L4-6','RULE-F05','SOURCE_RULE','ZN OI proxy'],['L4-6','RULE-G01','SOURCE_RULE','Quarterly shift'],['L4-6','RULE-G02','REQUIRES_BACKTEST','Q4 dollar seasonality'],['L4-6','RULE-G03','REQUIRES_BACKTEST','Early-year gold seasonality'],['L4-6','RULE-G04','REQUIRES_BACKTEST','Q4 NZD/JPY seasonality'],['L4-6','RULE-H01','SOURCE_RULE','1H dedicated structure'],['L4-6','RULE-H02','SOURCE_RULE','Unicorn'],['L4-6','RULE-I01','SOURCE_RULE','3/day cap'],['L4-6','RULE-I02','SOURCE_RULE','3-loss breaker'],['L4-6','RULE-I03','SOURCE_RULE','1.5-2% daily DD'],['L4-6','RULE-I04','REQUIRES_BACKTEST','Expectancy >=0.3R'],
  // L7-9
  ['L7-9','RULE-A01','SOURCE_RULE','Commodities to inflation/rates'],['L7-9','RULE-A02','SOURCE_RULE','Bonds/yields to DXY/FX/equities'],['L7-9','RULE-A03','SOURCE_RULE','Commodity FX'],['L7-9','RULE-A04','SOURCE_RULE','5-day ZN/DXY consolidation'],['L7-9','RULE-B01','SOURCE_RULE','52-week 50% COT line'],['L7-9','RULE-B02','REQUIRES_BACKTEST','10-15% OI drain'],['L7-9','RULE-B03','SOURCE_RULE','MWD sequence'],['L7-9','RULE-B04','SOURCE_RULE','4H rejection + displacement'],['L7-9','RULE-B05','REQUIRES_BACKTEST','MDS risk / no BE before 3R'],['L7-9','RULE-C01','SOURCE_RULE','Weekly 1H OSOK'],['L7-9','RULE-C02','SOURCE_RULE','Six weekly templates'],['L7-9','RULE-C03','SOURCE_RULE','Dynamic quadrants'],['L7-9','RULE-C04','SOURCE_RULE','1.27/1.62/2.0 targets'],['L7-9','RULE-D01','SOURCE_RULE','CBDR'],['L7-9','RULE-D02','REJECTED','ADR-5 NY lockout conflict retained'],['L7-9','RULE-D03','REQUIRES_BACKTEST','Tue/Wed timing'],['L7-9','RULE-E01','SOURCE_RULE','Offset Accumulation / IFVG'],['L7-9','RULE-E02','SOURCE_RULE','Asian scalp'],['L7-9','RULE-E03','SOURCE_RULE','NY scalp'],['L7-9','RULE-F01','SOURCE_RULE','ES/NQ SMT'],['L7-9','RULE-F02','REQUIRES_BACKTEST','CANSLIM'],['L7-9','RULE-F03','SOURCE_RULE','BTC/alt SMT'],
  // Hermes
  ['HERMES','RULE-A01','SOURCE_RULE','Hermes 1-Bar/2-Bar'],['HERMES','RULE-A02','SOURCE_RULE','Inside-bar neutralization'],['HERMES','RULE-A03','SOURCE_RULE','Confluence trigger'],['HERMES','RULE-B01','REQUIRES_BACKTEST','PCR day-4 DOL'],['HERMES','RULE-B02','SOURCE_RULE','PCR day-5 extension/invalidation'],['HERMES','RULE-B03','SOURCE_RULE','PCR invalidation filters'],['HERMES','RULE-C01','SOURCE_RULE','SIREN retail fade'],['HERMES','RULE-C02','SOURCE_RULE','SIREN 5m break + FVG inversion'],['HERMES','RULE-D01','REQUIRES_BACKTEST','SNAKE first-third sweep'],['HERMES','RULE-D02','REQUIRES_BACKTEST','SNAKE Gann thirds'],['HERMES','RULE-E01','SOURCE_RULE','SAC two-candle sweep/close'],['HERMES','RULE-E02','REQUIRES_BACKTEST','SAC opposite-extreme target'],['HERMES','RULE-F01','SOURCE_RULE','WICK wick behind displacement'],['HERMES','RULE-F02','SOURCE_RULE','WICK invalidation flip'],['HERMES','RULE-G01','SOURCE_RULE','20-day COT bias lock'],['HERMES','RULE-G02','DATA_DEPENDENT','EUR/GBP selector'],['HERMES','RULE-G03','REQUIRES_BACKTEST','20Y/10Y seasonality consensus'],['HERMES','RULE-G04','DATA_DEPENDENT','Treasury auction tails'],['HERMES','RULE-G05','ENGINEERING_ADDITION','Demon Finder 10 strikes'],['HERMES','RULE-G06','SOURCE_RULE','Half-tolerance risk / 3-loss breaker'],
].map(([scope,id,status,title]) => ({ scope,id,status,title })));

const body=(c:Candle)=>Math.abs(c.close-c.open);
const rng=(c:Candle)=>Math.max(c.high-c.low,1e-9);
const maxH=(c:Candle[])=>c.length?Math.max(...c.map(x=>x.high)):0;
const minL=(c:Candle[])=>c.length?Math.min(...c.map(x=>x.low)):0;
const med=(a:number[])=>{const s=a.slice().sort((x,y)=>x-y);return s[Math.floor(s.length/2)]??0};
const atr=(c:Candle[],n=14)=>{if(c.length<n+1)return 0;const out:number[]=[];for(let i=c.length-n;i<c.length;i++){const p=c[i-1]??c[i];out.push(Math.max(c[i].high-c[i].low,Math.abs(c[i].high-p.close),Math.abs(c[i].low-p.close)));}return med(out)};
const between=(x:number,a:number,b:number)=>x>=Math.min(a,b)&&x<=Math.max(a,b);
function nyMinutes(ts:number){const s=new Date(ts).toLocaleTimeString('en-US',{timeZone:'America/New_York',hour12:false,hour:'2-digit',minute:'2-digit'}).split(':');return Number(s[0])*60+Number(s[1]);}
function inKillzone(ts:number){const m=nyMinutes(ts);return (m>=120&&m<=300)||(m>=420&&m<=600);}
function session(ts:number){const m=nyMinutes(ts);if(m>=120&&m<=300)return 'LONDON_OPEN';if(m>=420&&m<=600)return 'NEW_YORK_OPEN';if(m>=1200&&m<=1350)return 'ASIAN_SCALP';return 'OUT_OF_SESSION';}
function validCandles(c:Candle[]){return c.filter(x=>Number.isFinite(x.open)&&Number.isFinite(x.high)&&Number.isFinite(x.low)&&Number.isFinite(x.close)&&x.high>=Math.max(x.open,x.close)&&x.low<=Math.min(x.open,x.close)&&x.time>0)}
function fourPoint(c:Candle[]){if(c.length<8)return {bull:false,bear:false};const p1=c[c.length-8],p2=c[c.length-6],p3=c[c.length-4],p4=c[c.length-2];return {bull:p3.low>p1.low&&p4.high>p2.high&&p4.close>p2.high,bear:p3.high<p1.high&&p4.low<p2.low&&p4.close<p2.low};}
function buildStructure(c:Candle[]):StructureSnapshot{
  const clean:Candle[]=[];let inside=0;for(const x of c){const p=clean[clean.length-1];if(p&&x.high<=p.high&&x.low>=p.low){inside++;continue;}clean.push(x);}
  const fp=fourPoint(clean);const highs:number[]=[];const lows:number[]=[];for(let i=1;i<clean.length-1;i++){if(clean[i].high>clean[i-1].high&&clean[i].high>clean[i+1].high)highs.push(clean[i].high);if(clean[i].low<clean[i-1].low&&clean[i].low<clean[i+1].low)lows.push(clean[i].low);}
  const last=c[c.length-1],prev=c[c.length-2];const hi=maxH(c.slice(-12,-1)),lo=minL(c.slice(-12,-1));const bos=last.close>hi||last.close<lo;const mss=(prev.close<lo&&last.close>prev.high)||(prev.close>hi&&last.close<prev.low);
  return {bias:fp.bull?'BULLISH':fp.bear?'BEARISH':'NEUTRAL',bullishFourPoint:fp.bull,bearishFourPoint:fp.bear,strongHigh:fp.bear?(highs[highs.length-1]??null):null,strongLow:fp.bull?(lows[lows.length-1]??null):null,weakHigh:highs[highs.length-2]??null,weakLow:lows[lows.length-2]??null,bos,mss,choch:mss,insideBarsNeutralized:inside,protectedIth:highs[highs.length-1]??null,protectedItl:lows[lows.length-1]??null};
}
function pools(c:Candle[]):LiquidityPool[]{const p:LiquidityPool[]=[];const look=c.slice(-60);for(let i=1;i<look.length-1;i++){if(look[i].high>look[i-1].high&&look[i].high>look[i+1].high)p.push({type:'BSL',price:look[i].high,time:look[i].time,strength:'STRONG'});if(look[i].low<look[i-1].low&&look[i].low<look[i+1].low)p.push({type:'SSL',price:look[i].low,time:look[i].time,strength:'STRONG'});}const a=atr(c);const tol=.15*a;for(let i=0;i<look.length;i++)for(let j=i+1;j<look.length;j++){if(Math.abs(look[i].high-look[j].high)<=tol)p.push({type:'EQH',price:(look[i].high+look[j].high)/2,time:look[j].time,strength:'WEAK'});if(Math.abs(look[i].low-look[j].low)<=tol)p.push({type:'EQL',price:(look[i].low+look[j].low)/2,time:look[j].time,strength:'WEAK'});}return p.slice(-32)}
function zones(c:Candle[],tf:string):Zone[]{const out:Zone[]=[];for(let i=Math.max(0,c.length-30);i<c.length-2;i++){const a=c[i],b=c[i+1],d=c[i+2];const bullF=d.low>a.high,bearF=d.high<a.low;const strong=body(d)>=Math.max(med(c.slice(Math.max(0,i-10),i).map(body)),1e-9)*1.25;if(strong){if(a.close<a.open&&d.close>d.open){const top=Math.max(a.high,b.high),bot=Math.min(a.low,b.low);out.push({type:'BULLISH_OB',top,bottom:bot,mt:bot+.5*(top-bot),timeframe:tf,valid:true});}if(a.close>a.open&&d.close<d.open){const top=Math.max(a.high,b.high),bot=Math.min(a.low,b.low);out.push({type:'BEARISH_OB',top,bottom:bot,mt:bot+.5*(top-bot),timeframe:tf,valid:true});}}if(bullF)out.push({type:'BULLISH_FVG',top:d.low,bottom:a.high,mt:a.high+.5*(d.low-a.high),timeframe:tf,valid:true});if(bearF)out.push({type:'BEARISH_FVG',top:a.low,bottom:d.high,mt:d.high+.5*(a.low-d.high),timeframe:tf,valid:true});}return out;}
function riskState(cfg:EngineConfig,ctx:EngineContext):RiskState{const r=ctx.risk??{};return {accountBalance:r.accountBalance??10000,currentRiskPct:r.currentRiskPct??cfg.riskPct,dailyLossPct:r.dailyLossPct??0,dailyTrades:r.dailyTrades??0,maxDailyTrades:r.maxDailyTrades??cfg.maxDailyTrades,consecutiveLosses:r.consecutiveLosses??0,maxConsecutiveLosses:r.maxConsecutiveLosses??cfg.maxConsecutiveLosses,consecutiveWins:r.consecutiveWins??0,demonStrikes:r.demonStrikes??0,maxDemonStrikes:r.maxDemonStrikes??10,weeklyOsokTrades:r.weeklyOsokTrades??0,maxWeeklyOsokTrades:r.maxWeeklyOsokTrades??1,tradingEnabled:r.tradingEnabled??true};}
function ev(strategy:Strategy,family:string,applicable:boolean,status:ValidationStatus,side:Side|null,entry:number,sl:number,tp:number,score:number,grade:Grade,reason:string,ids:string[],sts:RuleStatus[],components:string[],warnings:string[]=[]):StrategyEvaluation{return {strategy,family,applicable,status,side,entry,sl,tp,rrr:Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9),score,grade,reason,ruleIds:ids,ruleStatuses:sts,components,warnings};}

function pcr(d:Candle[],cfg:EngineConfig):StrategyEvaluation{
  if(d.length<5)return ev('PCR','HERMES',false,'NO_TRADE',null,0,0,0,0,null,'PCR_INSUFFICIENT_DAILY_DATA',['RULE-B01'],['REQUIRES_BACKTEST'],[]);
  const b1=d[d.length-4],b2=d[d.length-3],b3=d[d.length-2];const outside=(b2.high>b1.high&&b2.low<b1.low)||(b3.high>b2.high&&b3.low<b2.low);const sell=b2.high>b1.high&&b2.high>b3.high&&!outside;const buy=b2.low<b1.low&&b2.low<b3.low&&!outside;if(!sell&&!buy)return ev('PCR','HERMES',true,'NO_TRADE',null,0,0,0,0,null,'PCR_NOT_CONFIRMED',['RULE-B01','RULE-B02','RULE-B03'],['REQUIRES_BACKTEST','SOURCE_RULE','SOURCE_RULE'],['PCR']);
  const s:Side=sell?'SHORT':'LONG';const entry=s==='SHORT'?(b2.high+b3.low)/2:(b2.low+b3.high)/2;const sl=s==='SHORT'?b2.high:b2.low;const tp=s==='SHORT'?b3.low:b3.high;const r=Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);return ev('PCR','HERMES',true,r>=cfg.minRRR?'SIGNAL':'NO_TRADE',s,entry,sl,tp,r>=cfg.minRRR?82:56,r>=3?'A+':r>=cfg.minRRR?'A':null,r>=cfg.minRRR?'PCR_READY':'RRR_BELOW_CORE_MIN',['RULE-B01','RULE-B02','RULE-B03'],['REQUIRES_BACKTEST','SOURCE_RULE','SOURCE_RULE'],['PCR','DOL','OUTSIDE_BAR_FILTER']);
}
function snake(curr:Candle,prev:Candle,elapsed:number|undefined):StrategyEvaluation{if(elapsed===undefined)return ev('SNAKE','HERMES',true,'NO_TRADE',null,0,0,0,0,null,'FIRST_THIRD_TIMING_REQUIRED',['RULE-D01','RULE-D02'],['REQUIRES_BACKTEST','REQUIRES_BACKTEST'],['SNAKE']);if(elapsed>.333)return ev('SNAKE','HERMES',true,'NO_TRADE',null,0,0,0,0,null,'SNAKE_FIRST_THIRD_EXPIRED',['RULE-D01','RULE-D02'],['REQUIRES_BACKTEST','REQUIRES_BACKTEST'],['SNAKE','GANN_THIRDS']);const sell=curr.high>prev.high&&curr.close<=prev.high;const buy=curr.low<prev.low&&curr.close>=prev.low;if(!sell&&!buy)return ev('SNAKE','HERMES',true,'NO_TRADE',null,0,0,0,0,null,'SNAKE_SWEEP_NOT_CONFIRMED',['RULE-D01','RULE-D02'],['REQUIRES_BACKTEST','REQUIRES_BACKTEST'],['SNAKE']);const s:Side=sell?'SHORT':'LONG';const entry=curr.close,sl=s==='SHORT'?curr.high:curr.low,tp=curr.open;const r=Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);return ev('SNAKE','HERMES',true,'SIGNAL',s,entry,sl,tp,r>=2?80:65,r>=2?'A':'B','SNAKE_RETURN_TO_OPEN',['RULE-D01','RULE-D02'],['REQUIRES_BACKTEST','REQUIRES_BACKTEST'],['SNAKE','RETURN_TO_OPEN'],['80% return claim is not treated as guaranteed']);}
function sac(curr:Candle,prev:Candle):StrategyEvaluation{const sell=curr.high>prev.high&&curr.close<prev.low;const buy=curr.low<prev.low&&curr.close>prev.high;if(!sell&&!buy)return ev('SAC','HERMES',true,'NO_TRADE',null,0,0,0,0,null,'SAC_NOT_CONFIRMED',['RULE-E01','RULE-E02'],['SOURCE_RULE','REQUIRES_BACKTEST'],['SAC']);const s:Side=sell?'SHORT':'LONG';const entry=curr.close,sl=s==='SHORT'?curr.high:curr.low,tp=s==='SHORT'?prev.low:prev.high;const r=Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);return ev('SAC','HERMES',true,r>=DEFAULT_CONFIG.minRRR?'SIGNAL':'NO_TRADE',s,entry,sl,tp,r>=DEFAULT_CONFIG.minRRR?80:54,r>=DEFAULT_CONFIG.minRRR?'A':null,r>=DEFAULT_CONFIG.minRRR?'SAC_READY':'RRR_BELOW_CORE_MIN',['RULE-E01','RULE-E02'],['SOURCE_RULE','REQUIRES_BACKTEST'],['SAC','SWEEP','FULL_BODY_CLOSE']);}
function wick(c:Candle[],structure:StructureSnapshot):StrategyEvaluation{if(c.length<10)return ev('WICK','HERMES',false,'NO_TRADE',null,0,0,0,0,null,'WICK_INSUFFICIENT_DATA',['RULE-F01','RULE-F02'],['SOURCE_RULE','SOURCE_RULE'],[]);const p=c[c.length-2],l=c[c.length-1],disp=body(p)>med(c.slice(-12,-2).map(body))*1.25;const up=p.high-Math.max(p.open,p.close),dn=Math.min(p.open,p.close)-p.low;const sell=disp&&up>body(p)&&l.close<=p.high, buy=disp&&dn>body(p)&&l.close>=p.low;if(!sell&&!buy)return ev('WICK','HERMES',true,'NO_TRADE',null,0,0,0,0,null,'WICK_RETEST_NOT_CONFIRMED',['RULE-F01','RULE-F02'],['SOURCE_RULE','SOURCE_RULE'],['WICK','DISPLACEMENT']);const s:Side=sell?'SHORT':'LONG';const entry=l.close,sl=s==='SHORT'?p.high:p.low,tp=s==='SHORT'?(structure.weakLow??minL(c.slice(-20))):(structure.weakHigh??maxH(c.slice(-20)));const r=Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);return ev('WICK','HERMES',true,r>=DEFAULT_CONFIG.minRRR?'SIGNAL':'NO_TRADE',s,entry,sl,tp,r>=DEFAULT_CONFIG.minRRR?79:53,r>=DEFAULT_CONFIG.minRRR?'A':null,r>=DEFAULT_CONFIG.minRRR?'WICK_READY':'RRR_BELOW_CORE_MIN',['RULE-F01','RULE-F02'],['SOURCE_RULE','SOURCE_RULE'],['WICK','FIRST_RETEST','INVALIDATION_FLIP']);}
function siren(c5:Candle[],h1:Candle[],structure:StructureSnapshot):StrategyEvaluation{if(c5.length<20||h1.length<10)return ev('SIREN','HERMES',false,'NO_TRADE',null,0,0,0,0,null,'SIREN_REQUIRES_MTF_DATA',['RULE-C01','RULE-C02'],['SOURCE_RULE','SOURCE_RULE'],[]);const last=c5[c5.length-1],prev=c5[c5.length-2];const mssBull=prev.close<minL(c5.slice(-12,-2))&&last.close>prev.high,mssBear=prev.close>maxH(c5.slice(-12,-2))&&last.close<prev.low;const s:Side|null=mssBull?'LONG':mssBear?'SHORT':null;const hSide=structure.bias==='BULLISH'?'LONG':structure.bias==='BEARISH'?'SHORT':null; if(!s||s!==hSide)return ev('SIREN','HERMES',true,'NO_TRADE',null,0,0,0,0,null,'SIREN_5M_AND_1H_ALIGNMENT_NOT_CONFIRMED',['RULE-C01','RULE-C02'],['SOURCE_RULE','SOURCE_RULE'],['SIREN','1H_POI','5M_STRUCTURE','FVG_INVERSION']);const entry=last.close,sl=s==='LONG'?last.low:last.high,tp=s==='LONG'?maxH(c5.slice(-30)):minL(c5.slice(-30));const r=Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);return ev('SIREN','HERMES',true,r>=3?'SIGNAL':'NO_TRADE',s,entry,sl,tp,r>=3?81:55,r>=3?'A':null,r>=3?'SIREN_READY':'RRR_BELOW_3R',['RULE-C01','RULE-C02'],['SOURCE_RULE','SOURCE_RULE'],['SIREN','RETAIL_FADE','5M_FVG_INVERSION']);}
function mds(c4h:Candle[],daily:Candle[],macro:MacroContext|undefined):StrategyEvaluation{if(macro?.cotAligned!==true||macro.cot52WeekCommercialPercentile===undefined||macro.openInterestDrainPct===undefined)return ev('MDS','L7_MACRO_SWING',false,'NO_TRADE',null,0,0,0,0,null,'MDS_REQUIRES_COT_AND_OI_DATA',['RULE-B01','RULE-B02','RULE-B03','RULE-B04','RULE-B05'],['SOURCE_RULE','REQUIRES_BACKTEST','SOURCE_RULE','SOURCE_RULE','REQUIRES_BACKTEST'],['MDS'],['No fabricated macro values']);const longOk=macro.cot52WeekCommercialPercentile>=50&&macro.openInterestDrainPct>=10&&macro.openInterestDrainPct<=15&&fourPoint(daily).bull;if(!longOk)return ev('MDS','L7_MACRO_SWING',true,'NO_TRADE','LONG',0,0,0,0,null,'MDS_MACRO_CONDITIONS_NOT_MET',['RULE-B01','RULE-B02','RULE-B03','RULE-B04','RULE-B05'],['SOURCE_RULE','REQUIRES_BACKTEST','SOURCE_RULE','SOURCE_RULE','REQUIRES_BACKTEST'],['MDS','52W_COT','OI_DRAIN']);const last=c4h[c4h.length-1],prev=c4h[c4h.length-2];const rejection=last.low<prev.low&&(Math.min(last.open,last.close)-last.low)>body(last);const disp=body(last)>med(c4h.slice(-10,-1).map(body))*1.25;if(!rejection||!disp)return ev('MDS','L7_MACRO_SWING',true,'NO_TRADE','LONG',0,0,0,0,null,'MDS_4H_TRIGGER_NOT_CONFIRMED',['RULE-B03','RULE-B04'],['SOURCE_RULE','SOURCE_RULE'],['MDS','4H_REJECTION','DISPLACEMENT']);const entry=last.close,sl=last.low,tp=maxH(daily.slice(-60)),r=Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);return ev('MDS','L7_MACRO_SWING',true,r>=3?'SIGNAL':'NO_TRADE','LONG',entry,sl,tp,r>=3?88:57,r>=3?'A+':null,r>=3?'MDS_READY':'RRR_BELOW_3R',['RULE-B01','RULE-B02','RULE-B03','RULE-B04','RULE-B05'],['SOURCE_RULE','REQUIRES_BACKTEST','SOURCE_RULE','SOURCE_RULE','REQUIRES_BACKTEST'],['MDS','MWD','52W_COT','OI_DRAIN']);}
function osok(c1h:Candle[],ctx:EngineContext,now:number):StrategyEvaluation{if((ctx.weekly?.osokTradesTakenThisWeek??0)>=1)return ev('OSOK','L7_WEEKLY_KNOCKOUT',true,'NO_TRADE',null,0,0,0,0,null,'OSOK_WEEKLY_TRADE_ALREADY_CONSUMED',['RULE-C01','RULE-C02'],['SOURCE_RULE','SOURCE_RULE'],['OSOK']);if(ctx.weekly?.template==='SEEK_AND_DESTROY')return ev('OSOK','L7_WEEKLY_KNOCKOUT',true,'NO_TRADE',null,0,0,0,0,null,'SEEK_AND_DESTROY_REJECTED',['RULE-C02'],['REJECTED'],['OSOK','WEEKLY_TEMPLATE']);const v=ctx.volatility??{};if((v.cbdrRangePips??0)>40)return ev('OSOK','L7_WEEKLY_KNOCKOUT',true,'NO_TRADE',null,0,0,0,0,null,'CBDR_TOO_WIDE',['RULE-D01'],['SOURCE_RULE'],['CBDR']);const l=c1h[c1h.length-1],lo=minL(c1h.slice(-120)),hi=maxH(c1h.slice(-120)),q=(l.close-lo)/Math.max(hi-lo,1e-9);const s:Side=q<=.5?'LONG':q>=.5?'SHORT':null;if(!s)return ev('OSOK','L7_WEEKLY_KNOCKOUT',true,'NO_TRADE',null,0,0,0,0,null,'QUADRANT_UNCLEAR',['RULE-C03'],['SOURCE_RULE'],['QUADRANTS']);const entry=l.close,sl=s==='LONG'?l.low:l.high,dist=Math.abs(entry-sl),tp=entry+(s==='LONG'?1:-1)*dist*1.62,r=Math.abs(tp-entry)/Math.max(dist,1e-9);const ok=inKillzone(now)&&r>=3;return ev('OSOK','L7_WEEKLY_KNOCKOUT',true,ok?'SIGNAL':'NO_TRADE',s,entry,sl,tp,ok?90:58,ok?'A+':null,ok?'OSOK_READY':'OSOK_KILLZONE_OR_RRR',['RULE-C01','RULE-C02','RULE-C03','RULE-C04'],['SOURCE_RULE','SOURCE_RULE','SOURCE_RULE','SOURCE_RULE'],['OSOK','QUADRANT','1.62_EXTENSION']);}
function offset(c:Candle[]):StrategyEvaluation{if(c.length<8)return ev('OFFSET_IFVG','L8_INTRADAY',false,'NO_TRADE',null,0,0,0,0,null,'IFVG_INSUFFICIENT_DATA',['RULE-E01'],['SOURCE_RULE'],[]);const a=c[c.length-3],b=c[c.length-2],l=c[c.length-1],sell=b.high>a.high&&l.close<a.low,buy=b.low<a.low&&l.close>a.high;if(!sell&&!buy)return ev('OFFSET_IFVG','L8_INTRADAY',true,'NO_TRADE',null,0,0,0,0,null,'IFVG_NOT_CONFIRMED',['RULE-E01'],['SOURCE_RULE'],['OFFSET_ACCUMULATION','IFVG']);const s:Side=sell?'SHORT':'LONG',entry=l.close,sl=s==='SHORT'?b.high:b.low,tp=s==='SHORT'?a.low:a.high,r=Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);return ev('OFFSET_IFVG','L8_INTRADAY',true,r>=1.5?'SIGNAL':'NO_TRADE',s,entry,sl,tp,r>=1.5?74:54,r>=1.5?'B':null,r>=1.5?'OFFSET_IFVG_READY':'RRR_BELOW_SCALP_MIN',['RULE-E01'],['SOURCE_RULE'],['OFFSET_ACCUMULATION','IFVG']);}
function scalp(c:Candle[],now:number,kind:'ASIAN_SCALP'|'NY_SCALP'):StrategyEvaluation{const m=nyMinutes(now);const active=kind==='ASIAN_SCALP'?m>=1200&&m<=1350:m>=420&&m<=600;if(!active)return ev(kind,'L8_SCALPING',true,'NO_TRADE',null,0,0,0,0,null,kind==='ASIAN_SCALP'?'ASIAN_WINDOW_CLOSED':'NY_WINDOW_CLOSED',[kind==='ASIAN_SCALP'?'RULE-E02':'RULE-E03'],['SOURCE_RULE'],['SESSION']);const l=c[c.length-1],s:Side=l.close>=l.open?'LONG':'SHORT',entry=l.close,sl=s==='LONG'?l.low:l.high,tp=entry+(s==='LONG'?1:-1)*Math.abs(entry-sl)*1.5;return ev(kind,'L8_SCALPING',true,'SIGNAL',s,entry,sl,tp,65,'B',kind==='ASIAN_SCALP'?'ASIAN_SCALP_READY':'NY_SCALP_READY',[kind==='ASIAN_SCALP'?'RULE-E02':'RULE-E03'],['SOURCE_RULE'],['SCALP','SESSION']);}

function applyGates(e:StrategyEvaluation,c:Candle[],structure:StructureSnapshot,macro:MacroContext|undefined,vol:VolatilityContext|undefined,r:RiskState,ctx:EngineContext,now:number,cfg:EngineConfig):StrategyEvaluation{
  if(!e.applicable)return e;
  if(!r.tradingEnabled)return {...e,status:'NO_TRADE',reason:'ACCOUNT_FROZEN'};
  if(r.demonStrikes>=r.maxDemonStrikes)return {...e,status:'NO_TRADE',reason:'DEMON_FINDER_ACCOUNT_LOCKED'};
  if(r.consecutiveLosses>=r.maxConsecutiveLosses)return {...e,status:'NO_TRADE',reason:'CIRCUIT_BREAKER_TRIGGERED_3_LOSSES'};
  if(r.dailyTrades>=r.maxDailyTrades)return {...e,status:'NO_TRADE',reason:'MAX_DAILY_TRADES_EXCEEDED'};
  if(r.dailyLossPct>=cfg.dailyLossLimitPct)return {...e,status:'NO_TRADE',reason:'DAILY_DRAWDOWN_LIMIT_REACHED'};
  if(macro?.newsLock)return {...e,status:'NO_TRADE',reason:'HIGH_IMPACT_NEWS_LOCK'};
  if(vol?.spread!==undefined&&vol.averageSpread!==undefined&&vol.averageSpread>0&&vol.spread>2*vol.averageSpread)return {...e,status:'NO_TRADE',reason:'SPREAD_SPIKE'};
  if(vol?.slippage!==undefined&&vol.averageSlippage!==undefined&&vol.averageSlippage>0&&vol.slippage>2*vol.averageSlippage)return {...e,status:'NO_TRADE',reason:'SLIPPAGE_SPIKE'};
  if(e.status==='SIGNAL'&&!inKillzone(now)&&e.strategy!=='ASIAN_SCALP')return {...e,status:'NO_TRADE',reason:'OUT_OF_KILLZONE'};
  if(e.status==='SIGNAL'&&structure.bias!=='NEUTRAL'&&e.side&&((structure.bias==='BULLISH'&&e.side==='SHORT')||(structure.bias==='BEARISH'&&e.side==='LONG'))&&e.strategy!=='MDS'&&e.strategy!=='SNAKE')return {...e,status:'NO_TRADE',reason:'FIGHTING_ORDER_FLOW'};
  const min=e.strategy==='MDS'||e.strategy==='OSOK'?cfg.mdsOsokMinRRR:e.family==='L8_SCALPING'||e.strategy==='OFFSET_IFVG'?cfg.scalpMinRRR:cfg.minRRR;
  if(e.status==='SIGNAL'&&e.rrr<min)return {...e,status:'NO_TRADE',reason:'RRR_BELOW_STRATEGY_MIN'};
  if(ctx.weekly?.template==='SEEK_AND_DESTROY'&&e.status==='SIGNAL')return {...e,status:'NO_TRADE',reason:'SEEK_AND_DESTROY_NO_TRADE'};
  return e;
}

export function analyze(symbol:string,input:Candle[],timeframe='5m',cfg:EngineConfig=DEFAULT_CONFIG,ctx:EngineContext={}):Analysis{
  const c=validCandles(input);const now=ctx.now??(c[c.length-1]?.time??Date.now());const r=riskState(cfg,ctx);if(c.length<30)return empty(symbol,timeframe,'INSUFFICIENT_DATA',r);
  const structure=buildStructure(c);const ar=atr(c);const ps=pools(c);const zs=zones(c,timeframe);const last=c[c.length-1];const prev=c[c.length-2];
  const ssl=ps.filter(x=>x.type==='SSL').sort((a,b)=>b.time-a.time)[0];const bsl=ps.filter(x=>x.type==='BSL').sort((a,b)=>b.time-a.time)[0];const sweep=(ssl?last.low<ssl.price&&last.close>=ssl.price:false)||(bsl?last.high>bsl.price&&last.close<=bsl.price:false);
  const f3=c[c.length-3];const bullF=f3.high<last.low;const bearF=f3.low>last.high;const ob=zs.some(z=>z.type.includes('OB')&&between(last.close,z.bottom,z.top));const breaker=zs.some(z=>z.type.includes('BREAKER')&&between(last.close,z.bottom,z.top));
  const rh=maxH(c.slice(-40)),rl=minL(c.slice(-40));const side:Side|null=structure.bias==='BULLISH'?'LONG':structure.bias==='BEARISH'?'SHORT':(sweep&&ssl?'LONG':sweep&&bsl?'SHORT':null);const ote=side==='LONG'?between(last.close,rl+(rh-rl)*.62,rl+(rh-rl)*.79):side==='SHORT'?between(last.close,rh-(rh-rl)*.79,rh-(rh-rl)*.62):false;
  const dol=side==='LONG'?maxH(c.slice(-60)):side==='SHORT'?minL(c.slice(-60)):0;
  const daily=c.length>=180?c.slice(-180):c;const h1=c.filter((_,i)=>i%12===0);const h4=c.filter((_,i)=>i%48===0);
  const evals=[pcr(daily,cfg),siren(c,h1,structure),snake(last,prev,ctx.elapsedFraction),sac(last,prev),wick(c,structure),mds(h4,daily,ctx.macro),osok(h1,ctx,now),offset(c),scalp(c,now,'ASIAN_SCALP'),scalp(c,now,'NY_SCALP')].map(e=>applyGates(e,c,structure,ctx.macro,ctx.volatility,r,ctx,now,cfg));
  const candidates=evals.filter(e=>e.status==='SIGNAL').sort((a,b)=>b.score-a.score);const best=candidates[0]??null;
  const entry=best?.entry??last.close;const sl=best?.sl??(side==='LONG'?(ssl?.price??last.low):(side==='SHORT'?(bsl?.price??last.high):last.close));const tp=best?.tp??(dol||last.close);const rrr=best?.rrr??Math.abs(tp-entry)/Math.max(Math.abs(entry-sl),1e-9);
  const reasons:string[]=[];if(!best)reasons.push(...Array.from(new Set(evals.map(e=>e.reason).filter(Boolean))));if(structure.bias==='NEUTRAL')reasons.push('NO_DIRECTIONAL_STRUCTURE');if(!inKillzone(now)&&!evals.some(e=>e.strategy==='ASIAN_SCALP'&&e.status==='SIGNAL'))reasons.push('OUT_OF_KILLZONE');if(!ob&&!breaker&&!ote&&!bullF&&!bearF)reasons.push('NO_VALID_POI');if(ctx.macro?.znDxySyncDays!==undefined&&ctx.macro.znDxySyncDays>=5)reasons.push('BOND_DXY_SYNC_CONSOLIDATION_PREDICTED');
  const trace:RuleTrace[]=RULEBOOK.map(x=>{const applied=best?best.ruleIds.includes(x.id):false;const structurePass=structure.bias!=='NEUTRAL';return {scope:x.scope,id:x.id,status:x.status,passed:applied||(x.scope==='L1-3'&&structurePass),reason:applied?'APPLIED_TO_SELECTED_SETUP':x.status==='REQUIRES_BACKTEST'?'REQUIRES_VALIDATION':'NOT_SELECTED_OR_DATA_UNAVAILABLE'};});
  const score=best?.score??Math.min(55,(structure.bias!=='NEUTRAL'?20:0)+(structure.bos?15:0)+(structure.mss?15:0)+(sweep?15:0)+((bullF||bearF)?10:0)+(ob?10:0)+(ote?10:0));
  return {symbol,timeframe,side:best?.side??side,bias:best?.side==='LONG'?'BULLISH':best?.side==='SHORT'?'BEARISH':structure.bias,bos:structure.bos,mss:structure.mss,sweep,fvg:bullF||bearF,orderBlock:ob,breaker,ote,liquidity:sweep?(ssl?'SSL_SWEEP':'BSL_SWEEP'):'UNMAPPED',dol:dol?dol.toFixed(5):'UNKNOWN',grade:best?.grade??null,rrr,entry,sl,tp,strategy:best?.strategy??null,status:best?.status??'NO_TRADE',reason:best?.reason??(reasons[0]??'NO_QUALIFIED_SETUP'),score,components:best?.components??['STRUCTURE','LIQUIDITY','PD_ARRAY','DOL','RISK_GATE'],structure,zones:zs,liquidityPools:ps,dolTarget:dol||null,rrrPolicy:best?.strategy==='MDS'||best?.strategy==='OSOK'?'3R+':best?.family.includes('SCALPING')||best?.strategy==='OFFSET_IFVG'?'1.5R+':'2.5R+',strategyEvaluations:evals,ruleTrace:trace,noTradeReasons:Array.from(new Set(reasons)),state:best?'SIGNAL_READY':'NO_TRADE',risk:r,sourceWarnings:['Percentages/probabilities and disputed thresholds remain marked for backtest or source-status handling.','Missing COT/DXY/bond/seasonality/news data is never fabricated.']};
}
function empty(symbol:string,timeframe:string,reason:string,r:RiskState):Analysis{return {symbol,timeframe,side:null,bias:'NEUTRAL',bos:false,mss:false,sweep:false,fvg:false,orderBlock:false,breaker:false,ote:false,liquidity:'UNKNOWN',dol:'UNKNOWN',grade:null,rrr:0,entry:0,sl:0,tp:0,strategy:null,status:'NO_TRADE',reason,score:0,components:[],structure:{bias:'NEUTRAL',bullishFourPoint:false,bearishFourPoint:false,strongHigh:null,strongLow:null,weakHigh:null,weakLow:null,bos:false,mss:false,choch:false,insideBarsNeutralized:0,protectedIth:null,protectedItl:null},zones:[],liquidityPools:[],dolTarget:null,rrrPolicy:'strategy-specific',strategyEvaluations:[],ruleTrace:RULEBOOK.map(x=>({scope:x.scope,id:x.id,status:x.status,passed:false,reason})),noTradeReasons:[reason],state:'NO_TRADE',risk:r,sourceWarnings:[]};}
export function positionSize(balance:number,riskPct:number,entry:number,sl:number,contractValue=1){const cash=balance*riskPct/100;const d=Math.abs(entry-sl);return d>0?cash/(d*contractValue):0;}
export function currentTraderFRisk(consecutiveWins:number,hadLoss:boolean,base=DEFAULT_CONFIG.baseRiskPct){if(hadLoss)return base;if(consecutiveWins>=5)return base;return Math.min(DEFAULT_CONFIG.maxRiskPct,base+.5*Math.min(consecutiveWins,3));}
export function nextRiskAfterTrade(result:'WIN'|'LOSS',consecutiveWins:number,base=DEFAULT_CONFIG.baseRiskPct){return result==='LOSS'||consecutiveWins>=5?base:Math.min(DEFAULT_CONFIG.maxRiskPct,base+.5);}
export function generateDemoCandles(seed:number,count:number,base:number):Candle[]{let x=seed>>>0,p=base;const out:Candle[]=[];const rnd=()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296};for(let i=0;i<count;i++){const o=p,drift=(rnd()-.47)*base*.004,vol=base*.003*(.65+rnd()),close=Math.max(1,o+drift),high=Math.max(o,close)+vol*rnd(),low=Math.min(o,close)-vol*rnd();p=close;out.push({time:Date.now()-(count-i)*300000,open:o,high,low,close,volume:500+rnd()*1200});}return out;}
