export type Category = 'chat'|'image'|'video'|'code'|'research'|'audio';
export type PricingPlan = { name:string; monthly?:number; annual?:number; custom?:boolean; features:string[]; verified:string; source:string };
export type Tool = { id:string; name:string; vendor:string; category:Category; hook:string; description:string; website:string; logo:string; featured:boolean; plans:PricingPlan[] };

export const categories:{id:'all'|Category;label:string;icon:string}[] = [
  {id:'all',label:'الكل',icon:'✦'}, {id:'chat',label:'محادثة',icon:'◉'}, {id:'image',label:'صور',icon:'◌'}, {id:'video',label:'فيديو',icon:'▶'}, {id:'code',label:'برمجة',icon:'⌘'}, {id:'research',label:'بحث',icon:'⌕'}, {id:'audio',label:'صوت',icon:'◖'}
];

export const seedTools:Tool[] = [
  {id:'chatgpt',name:'ChatGPT',vendor:'OpenAI',category:'chat',logo:'CG',hook:'المساعد الذي يفهمك بأي لغة، ويكتب ويحلل وينشئ الصور.',description:'يجمع في مساحة واحدة المحادثة الذكية، تحليل الملفات، إنشاء الصور، والبحث المتقدم. مناسب لمن يريد نقطة انطلاق واحدة لمعظم أعماله اليومية.',website:'https://chatgpt.com',featured:true,plans:[{name:'Plus',monthly:20,features:['نماذج متقدمة','أدوات متعددة','ميزات إنتاجية'],verified:'نموذجية — راجع المصدر',source:'https://openai.com/chatgpt/pricing/'},{name:'Pro',monthly:200,features:['استخدام أعلى','أولوية موسعة','قدرات متقدمة'],verified:'نموذجية — راجع المصدر',source:'https://openai.com/chatgpt/pricing/'}]},
  {id:'claude',name:'Claude',vendor:'Anthropic',category:'chat',logo:'CL',hook:'كتابة احترافية، برمجة معقدة، وفهم قوي للمستندات الطويلة.',description:'يمتاز بجودة كتابة عالية ودقة في اتباع التعليمات، ويعد خياراً قوياً للمطورين وأصحاب الأعمال الذين يحتاجون إلى التعامل مع نصوص ومهام مركبة.',website:'https://claude.ai',featured:true,plans:[{name:'Pro',monthly:20,features:['استخدام موسع','ميزات إنتاجية','أولوية أثناء الذروة'],verified:'نموذجية — راجع المصدر',source:'https://www.anthropic.com/pricing'}]},
  {id:'gemini',name:'Gemini',vendor:'Google',category:'chat',logo:'GE',hook:'ذكاء اصطناعي متصل بمنظومة Google ومستنداتك وملفاتك.',description:'مفيد لمن يعمل داخل منظومة Google ويحتاج إلى ربط المحادثة والبحث والمستندات والخدمات السحابية ضمن تجربة واحدة.',website:'https://gemini.google.com',featured:true,plans:[{name:'Google AI Pro',monthly:19.99,features:['ميزات AI متقدمة','تكامل Google','تخزين سحابي'],verified:'نموذجية — راجع المصدر',source:'https://one.google.com/about/google-ai-plans/'}]},
  {id:'midjourney',name:'Midjourney',vendor:'Midjourney',category:'image',logo:'MJ',hook:'صور فنية عالية الجودة للمصممين وصناع المحتوى البصري.',description:'أداة توليد صور قوية تستهدف العمل الإبداعي والمرئي، مع تحكم واسع في الأسلوب والتركيب والتفاصيل.',website:'https://www.midjourney.com',featured:true,plans:[{name:'Standard',monthly:30,features:['توليد واسع','وضع Relax','إنتاج مرئي احترافي'],verified:'نموذجية — راجع المصدر',source:'https://www.midjourney.com/account/'} ,{name:'Pro',monthly:60,features:['خصوصية Stealth','ميزات أعلى','إنتاج واسع'],verified:'نموذجية — راجع المصدر',source:'https://www.midjourney.com/account/'}]},
  {id:'perplexity',name:'Perplexity',vendor:'Perplexity AI',category:'research',logo:'PX',hook:'بحث ذكي يجيبك مع مصادر بدل قائمة نتائج فقط.',description:'يركز على البحث والاستدلال وتجميع المعلومات مع إظهار المصادر، وهو مناسب للأبحاث السريعة والمقارنات وصناعة المسودات الموثقة.',website:'https://www.perplexity.ai',featured:true,plans:[{name:'Pro',monthly:20,features:['بحث متقدم','نماذج متعددة','رفع وتحليل ملفات'],verified:'نموذجية — راجع المصدر',source:'https://www.perplexity.ai/pro'}]},
  {id:'copilot',name:'GitHub Copilot',vendor:'GitHub',category:'code',logo:'GH',hook:'مساعدك البرمجي داخل محرر الكود أثناء العمل.',description:'يندمج مباشرة مع بيئة التطوير لمساعدتك في الإكمال والشرح وتوليد الكود وتسريع دورة التطوير اليومية.',website:'https://github.com/features/copilot',featured:true,plans:[{name:'Pro',monthly:10,features:['اقتراحات كود','مساعدة داخل IDE','ميزات AI للمطورين'],verified:'نموذجية — راجع المصدر',source:'https://github.com/features/copilot#pricing'}]},
  {id:'runway',name:'Runway',vendor:'Runway',category:'video',logo:'RW',hook:'مختبر إبداعي لتحويل الأفكار إلى فيديو بالذكاء الاصطناعي.',description:'منصة متخصصة في إنشاء وتحرير الفيديو بالذكاء الاصطناعي، مناسبة لصناع المحتوى والحملات الإبداعية والنماذج الأولية.',website:'https://runwayml.com',featured:false,plans:[{name:'Standard',monthly:15,features:['رصيد شهري','توليد فيديو','أدوات إبداعية'],verified:'نموذجية — راجع المصدر',source:'https://runwayml.com/pricing/'}]},
  {id:'elevenlabs',name:'ElevenLabs',vendor:'ElevenLabs',category:'audio',logo:'EL',hook:'أصوات طبيعية لإنشاء التعليق الصوتي والمحتوى السمعي.',description:'حل قوي للصوت التوليدي والتعليق الصوتي والدبلجة والتطبيقات التي تحتاج إلى أصوات طبيعية قابلة للتخصيص.',website:'https://elevenlabs.io',featured:false,plans:[{name:'Starter',monthly:5,features:['توليد صوت','أصوات متعددة','الاستخدام التجاري وفق الخطة'],verified:'نموذجية — راجع المصدر',source:'https://elevenlabs.io/pricing'}]}
];

export const demoSettings={whatsappNumber:'963932067632',facebookUrl:'https://www.facebook.com/Alaabdalaziz?mibextid=ZbWKwL',whatsappMessage:'مرحبا، بدي استفسر عن اشتراك بإحدى أدوات الذكاء الاصطناعي عبر منصة أطلس'};
