import fs from 'node:fs';
import path from 'node:path';
import { ROOT, readJSON, makeT, rmDir, writeFile, copyDir, urlFor, filePathFor, SLUG_RE } from './lib/util.mjs';
import { renderHome } from './lib/page-home.mjs';
import { renderTool } from './lib/page-tool.mjs';
import { renderCatalog } from './lib/page-catalog.mjs';
import { renderContact } from './lib/page-contact.mjs';
const DIST=path.join(ROOT,'dist'),config=readJSON('site.config.json'),languages=config.languages,defaultLang=config.defaultLang,dicts={};
for(const lang of languages)dicts[lang.code]=readJSON(`i18n/${lang.code}.json`);const t=makeT(dicts,defaultLang),ctx={config,t,dicts,languages,defaultLang};
const contentDir=path.join(ROOT,'content');const all=fs.readdirSync(contentDir).filter(f=>f.endsWith('.json')).map(f=>readJSON(`content/${f}`)).filter(tool=>SLUG_RE.test(tool.slug||''));const published=all.filter(t=>t.meta?.status==='published');
rmDir(DIST);copyDir(path.join(ROOT,'src','styles'),path.join(DIST,'css','_src'));copyDir(path.join(ROOT,'src','js'),path.join(DIST,'js'));const assetsDir=path.join(ROOT,'src','assets');if(fs.existsSync(assetsDir))copyDir(assetsDir,path.join(DIST,'assets'));
const cssOrder=['fonts.css','tokens.css','base.css','depth.css','components/layout.css','components/motion.css','components/atlas.css','components/home.css','components/tool.css','components/pricing.css','components/contact.css','components/catalog.css'];const css=cssOrder.map(rel=>{const f=path.join(ROOT,'src','styles',rel);if(!fs.existsSync(f))throw new Error(`ملف CSS مفقود: src/styles/${rel}`);return `/* ===== ${rel} ===== */\n${fs.readFileSync(f,'utf8')}`}).join('\n\n');writeFile(path.join(DIST,'css','app.css'),css);rmDir(path.join(DIST,'css','_src'));
let pageCount=0;const write=(lang,rel,html)=>{const out=filePathFor(lang,defaultLang,rel).replace(/^\//,'');writeFile(path.join(DIST,out),html);pageCount++};for(const lang of languages.map(l=>l.code)){write(lang,'index.html',renderHome(ctx,lang,published));write(lang,'catalog.html',renderCatalog(ctx,lang,published));write(lang,'contact.html',renderContact(ctx,lang));for(const tool of all)write(lang,`tools/${tool.slug}.html`,renderTool(ctx,lang,tool))}
writeFile(path.join(DIST,'data','index.json'),JSON.stringify(published.map(tool=>({slug:tool.slug,name:tool.name,tagline:tool.tagline,category:tool.category,overall:tool.ratings?.overall??null,logo:tool.media?.logo?.url??null,urls:Object.fromEntries(languages.map(l=>[l.code,urlFor(l.code,defaultLang,`tools/${tool.slug}.html`)]))})),null,2));
const today=new Date().toISOString().slice(0,10),entries=[];for(const lang of languages.map(l=>l.code)){for(const rel of ['index.html','catalog.html','contact.html'])entries.push({lang,rel});for(const tool of published)entries.push({lang,rel:`tools/${tool.slug}.html`})}const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${entries.map(({lang,rel})=>`<url><loc>${config.baseUrl}${urlFor(lang,defaultLang,rel)}</loc><lastmod>${today}</lastmod>${languages.map(l=>`<xhtml:link rel="alternate" hreflang="${l.code}" href="${config.baseUrl}${urlFor(l.code,defaultLang,rel)}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${config.baseUrl}${urlFor(defaultLang,defaultLang,rel)}"/></url>`).join('\n')}</urlset>\n`;writeFile(path.join(DIST,'sitemap.xml'),sitemap);writeFile(path.join(DIST,'robots.txt'),`User-agent: *\nAllow: /\n\nSitemap: ${config.baseUrl}${config.basePath||''}/sitemap.xml\n`);writeFile(path.join(DIST,'_headers'),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  X-Frame-Options: DENY\n  Content-Security-Policy: default-src 'self'; img-src 'self' https: data:; style-src 'self'; script-src 'self'; connect-src 'self'; font-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'\n`);console.log(`✔ تم البناء — ${pageCount} صفحة، ${published.length} أداة منشورة → dist/`);